/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e

Explanation:
'e' is the letter that was added.
*/

// T : O(N), S : O(K)
class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<char> mp(26, 0);
        for (auto c : t)
            mp[c - 'a']++;
        for (auto c : s)
            mp[c - 'a']--;
        for (int i = 0; i < 26; i++) {
            if (mp[i]) {
                return 'a' + i;
            }
        }
        return 'x';
    }
};

//T : O(NlogN), S : O(1)
class Solution {
public:
    char findTheDifference(string s, string t) {
        sort(s.begin(), s.end());
        sort(t.begin(), t.end());
        for (int i = 0; i < t.length() - 1; i++) {
            if (s[i] != t[i])
                return t[i];
        }
        return t[t.length() - 1];
    }
};
